default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5

development:
  <<: *default
  host: 127.0.0.1
  username: signonotron2
  password: signonotron2
  database: signonotron2_development

test: &test
  <<: *default
  host: 127.0.0.1
  username: signonotron2
  password: signonotron2
  database: signonotron2_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
